In [1]:
# Import libraries
import pandas as pd
import sqlite3

In [5]:
# Load cleaned dataset
books_df = pd.read_csv(
    "../data/processed/books_cleaned.csv"
)

books_df.head()

,title,price,availability,rating,product_url,category,description,upc,tax,number_available,stock_quantity,stock_status,price_category
0,A Light in the Attic,51.77,In stock,3,http://books.toscrape.com/catalogue/a-light-in...,Poetry,It's hard to imagine a world without A Light i...,a897fe39b1053632,0.0,In stock (22 available),22.0,In Stock,High
1,Tipping the Velvet,53.74,In stock,1,http://books.toscrape.com/catalogue/tipping-th...,Historical Fiction,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,0.0,In stock (20 available),20.0,In Stock,High
2,Soumission,50.10,In stock,1,http://books.toscrape.com/catalogue/soumission...,Fiction,"Dans une France assez proche de la nÃ´tre, un ...",6957f44c3847a760,0.0,In stock (20 available),20.0,In Stock,High
3,Sharp Objects,47.82,In stock,4,http://books.toscrape.com/catalogue/sharp-obje...,Mystery,"WICKED above her hipbone, GIRL across her hear...",e00eb4fd7b871a48,0.0,In stock (20 available),20.0,In Stock,High
4,Sapiens: A Brief History of Humankind,54.23,In stock,5,http://books.toscrape.com/catalogue/sapiens-a-...,History,From a renowned historian comes a groundbreaki...,4165285e1663650f,0.0,In stock (20 available),20.0,In Stock,High

In [6]:
# Create database connection
conn = sqlite3.connect(
    "../data/books.db"
)

In [7]:
# Load data into SQLite
books_df.to_sql(
    "books",
    conn,
    if_exists="replace",
    index=False
)

1000

In [9]:
# Verify table creation
query = """
SELECT *
FROM books
LIMIT 5
"""

pd.read_sql_query(query,conn)

,title,price,availability,rating,product_url,category,description,upc,tax,number_available,stock_quantity,stock_status,price_category
0,A Light in the Attic,51.77,In stock,3,http://books.toscrape.com/catalogue/a-light-in...,Poetry,It's hard to imagine a world without A Light i...,a897fe39b1053632,0.0,In stock (22 available),22.0,In Stock,High
1,Tipping the Velvet,53.74,In stock,1,http://books.toscrape.com/catalogue/tipping-th...,Historical Fiction,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,0.0,In stock (20 available),20.0,In Stock,High
2,Soumission,50.10,In stock,1,http://books.toscrape.com/catalogue/soumission...,Fiction,"Dans une France assez proche de la nÃ´tre, un ...",6957f44c3847a760,0.0,In stock (20 available),20.0,In Stock,High
3,Sharp Objects,47.82,In stock,4,http://books.toscrape.com/catalogue/sharp-obje...,Mystery,"WICKED above her hipbone, GIRL across her hear...",e00eb4fd7b871a48,0.0,In stock (20 available),20.0,In Stock,High
4,Sapiens: A Brief History of Humankind,54.23,In stock,5,http://books.toscrape.com/catalogue/sapiens-a-...,History,From a renowned historian comes a groundbreaki...,4165285e1663650f,0.0,In stock (20 available),20.0,In Stock,High

In [10]:
# Check row count
query = """
SELECT COUNT(*) AS total_books
FROM books
"""

pd.read_sql_query(query,conn)

   total_books
0         1000

In [11]:
# Close connection
conn.close()