In [107]:
# Import libraries
import pandas as pd
import sqlite3

In [108]:
# Connect to SQLite database
conn = sqlite3.connect(
    "../data/books.db"
)

In [109]:
query = """
SELECT *
FROM books
LIMIT 5;
"""

pd.read_sql_query(query,conn)

,title,price,availability,rating,product_url,category,description,upc,tax,number_available,stock_quantity,stock_status,price_category
0,A Light in the Attic,51.77,In stock,3,http://books.toscrape.com/catalogue/a-light-in...,Poetry,It's hard to imagine a world without A Light i...,a897fe39b1053632,0.0,In stock (22 available),22.0,In Stock,High
1,Tipping the Velvet,53.74,In stock,1,http://books.toscrape.com/catalogue/tipping-th...,Historical Fiction,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,0.0,In stock (20 available),20.0,In Stock,High
2,Soumission,50.10,In stock,1,http://books.toscrape.com/catalogue/soumission...,Fiction,"Dans une France assez proche de la nÃ´tre, un ...",6957f44c3847a760,0.0,In stock (20 available),20.0,In Stock,High
3,Sharp Objects,47.82,In stock,4,http://books.toscrape.com/catalogue/sharp-obje...,Mystery,"WICKED above her hipbone, GIRL across her hear...",e00eb4fd7b871a48,0.0,In stock (20 available),20.0,In Stock,High
4,Sapiens: A Brief History of Humankind,54.23,In stock,5,http://books.toscrape.com/catalogue/sapiens-a-...,History,From a renowned historian comes a groundbreaki...,4165285e1663650f,0.0,In stock (20 available),20.0,In Stock,High

In [110]:
# Summary of missing data in the books dataset
query = """
SELECT
    COUNT(*) AS total_books,
    SUM(
        CASE
            WHEN category IS NULL
            THEN 1
            ELSE 0
        END
    ) AS missing_categories,
    SUM(
        CASE
            WHEN stock_quantity IS NULL
            THEN 1
            ELSE 0
        END
    ) AS missing_stock
FROM books;
"""
pd.read_sql_query(query,conn)

   total_books  missing_categories  missing_stock
0         1000                   8              8

In [111]:
# Books by category
query = """
SELECT
    category,
    COUNT(*) AS total_books
FROM books
WHERE category IS NOT NULL
AND category <> ''
GROUP BY category
ORDER BY total_books DESC;
"""

pd.read_sql_query(query,conn)

              category  total_books
0              Default          150
1           Nonfiction          110
2       Sequential Art           74
3        Add a comment           67
4              Fiction           65
5          Young Adult           54
6              Fantasy           46
7              Romance           35
8              Mystery           32
9       Food and Drink           30
10           Childrens           29
11  Historical Fiction           26
12            Classics           19
13              Poetry           18
14             History           18
15              Horror           17
16      Womens Fiction           16
17     Science Fiction           16
18             Science           14
19               Music           13
20            Business           12
21              Travel           11
22            Thriller           11
23          Philosophy           11
24               Humor           10
25       Autobiography            9
26            Religion            7
27          Psychology            7
28                 Art            7
29        Spirituality            6
30           New Adult            6
31   Christian Fiction            6
32    Sports and Games            5
33           Self Help            5
34           Biography            5
35              Health            4
36            Politics            3
37        Contemporary            3
38           Christian            3
39          Historical            2
40            Suspense            1
41       Short Stories            1
42           Parenting            1
43          Paranormal            1
44              Novels            1
45             Erotica            1
46            Cultural            1
47               Crime            1
48       Adult Fiction            1
49            Academic            1

In [112]:
# Total number of books by category
query = """
SELECT
    category,
    COUNT(*) AS total_books
FROM books
WHERE category IS NOT NULL
AND category <> ''
GROUP BY category
ORDER BY total_books DESC
LIMIT 10
"""

pd.read_sql_query(query,conn)

         category  total_books
0         Default          150
1      Nonfiction          110
2  Sequential Art           74
3   Add a comment           67
4         Fiction           65
5     Young Adult           54
6         Fantasy           46
7         Romance           35
8         Mystery           32
9  Food and Drink           30

In [113]:
# Top 10 most expensive books
query = """
SELECT
    title,
    price
FROM books
ORDER BY price DESC
LIMIT 10
"""

pd.read_sql_query(query,conn)

                                               title  price
0                 The Perfect Play (Play by Play #1)  59.99
1                  Last One Home (New Beginnings #1)  59.98
2                   Civilization and Its Discontents  59.95
3                     The Barefoot Contessa Cookbook  59.92
4                          The Diary of a Young Girl  59.90
5  The Bone Hunters (Lexy Vaughan & Steven Macaul...  59.71
6  Thomas Jefferson and the Tripoli Pirates: The ...  59.64
7                      Boar Island (Anna Pigeon #19)  59.48
8                          The Improbability of Love  59.45
9  The Man Who Mistook His Wife for a Hat and Oth...  59.45

In [114]:
# Average price of books by category
query = """
SELECT
    category,
    ROUND(
        AVG(price),
        2
    ) AS average_price
FROM books
WHERE category IS NOT NULL
AND category <> ''
GROUP BY category
ORDER BY average_price DESC
"""

pd.read_sql_query(query,conn)

              category  average_price
0             Suspense          58.33
1               Novels          54.81
2             Politics          53.61
3               Health          51.45
4            New Adult          46.38
5            Christian          42.50
6     Sports and Games          41.17
7            Self Help          40.62
8               Travel          39.79
9                  Art          39.40
10             Fantasy          39.18
11           Parenting          37.35
12             History          37.30
13              Poetry          37.12
14       Autobiography          37.05
15            Cultural          36.58
16            Classics          36.55
17        Contemporary          36.20
18      Womens Fiction          36.07
19             Fiction          36.07
20              Horror          35.95
21       Short Stories          35.88
22       Add a comment          35.80
23               Music          35.64
24         Young Adult          35.45
25        Spirituality          35.10
26      Sequential Art          34.66
27   Christian Fiction          34.39
28             Default          34.35
29          Nonfiction          34.26
30          Psychology          34.22
31             Romance          33.93
32     Science Fiction          33.80
33           Biography          33.66
34  Historical Fiction          33.64
35          Philosophy          33.56
36               Humor          33.50
37             Science          33.09
38           Childrens          32.64
39            Religion          32.57
40            Business          32.46
41             Mystery          31.72
42            Thriller          31.43
43      Food and Drink          31.41
44          Historical          22.83
45             Erotica          19.19
46          Paranormal          15.40
47       Adult Fiction          15.36
48            Academic          13.12
49               Crime          10.97

In [115]:
# Average rating of books by category
query = """
SELECT
    category,
    ROUND(
        AVG(rating),
        1
    ) AS average_rating
FROM books
WHERE category IS NOT NULL
AND category <> ''
GROUP BY category
ORDER BY average_rating DESC
LIMIT 10
"""

pd.read_sql_query(query,conn)

            category  average_rating
0             Novels             5.0
1            Erotica             5.0
2      Adult Fiction             5.0
3  Christian Fiction             4.2
4                Art             3.9
5             Health             3.8
6             Poetry             3.4
7              Humor             3.4
8        Young Adult             3.3
9       Spirituality             3.3

In [116]:
# Books with 5-star rating
query = """
SELECT
    title,
    category,
    price
FROM books
WHERE category IS NOT NULL
AND category <> ''
AND rating = 5
ORDER BY price DESC
"""

pd.read_sql_query(query,conn)

                                                 title        category  price
0                       The Barefoot Contessa Cookbook  Food and Drink  59.92
1                                Life Without a Recipe   Autobiography  59.04
2       Approval Junkie: Adventures in Caring Too Much   Autobiography  58.81
3    How to Speak Golf: An Illustrated Guide to Lin...         Default  58.32
4                                     Digital Fortress         Fiction  58.00
..                                                 ...             ...    ...
188                                The Darkest Corners     Young Adult  11.33
189                                 Dear Mr. Knightley         Fiction  11.21
190  The Power Greens Cookbook: 140 Delicious Super...  Food and Drink  11.05
191                               Greek Mythic History         Default  10.23
192                         An Abundance of Katherines     Young Adult  10.00

[193 rows x 3 columns]

In [117]:
# Total number of 5-star books by category
query = """
SELECT
    category,
    COUNT(*) AS five_star_books
FROM books
WHERE category IS NOT NULL
AND category <> ''
AND rating = 5
GROUP BY category
ORDER BY five_star_books DESC
"""

pd.read_sql_query(query,conn)

              category  five_star_books
0              Default               29
1           Nonfiction               20
2              Fiction               17
3          Young Adult               15
4       Sequential Art               12
5              Fantasy                9
6   Historical Fiction                8
7        Add a comment                8
8       Food and Drink                7
9               Poetry                5
10             Mystery                5
11             Romance                4
12               Music                4
13               Humor                4
14             History                4
15      Womens Fiction                3
16        Spirituality                3
17   Christian Fiction                3
18           Childrens                3
19            Business                3
20       Autobiography                3
21            Thriller                2
22             Science                2
23          Philosophy                2
24           New Adult                2
25              Horror                2
26              Health                2
27              Travel                1
28    Sports and Games                1
29           Self Help                1
30     Science Fiction                1
31            Religion                1
32              Novels                1
33          Historical                1
34             Erotica                1
35        Contemporary                1
36           Christian                1
37                 Art                1
38       Adult Fiction                1

In [118]:
# Total stock quantity of books by category
query = """
SELECT
    category,
    SUM(stock_quantity) AS total_stock
FROM books
WHERE category IS NOT NULL
AND category <> ''
GROUP BY category
ORDER BY total_stock DESC
"""

pd.read_sql_query(query,conn)

              category  total_stock
0              Default       1336.0
1           Nonfiction        975.0
2       Sequential Art        682.0
3              Fiction        588.0
4        Add a comment        516.0
5          Young Adult        464.0
6              Fantasy        364.0
7       Food and Drink        319.0
8              Mystery        290.0
9              Romance        269.0
10              Poetry        229.0
11           Childrens        229.0
12  Historical Fiction        194.0
13             History        181.0
14              Horror        136.0
15            Business        133.0
16     Science Fiction        125.0
17            Thriller        119.0
18               Music        111.0
19             Science        105.0
20              Travel         89.0
21      Womens Fiction         87.0
22               Humor         84.0
23          Philosophy         82.0
24        Spirituality         69.0
25                 Art         65.0
26            Religion         60.0
27           Self Help         59.0
28       Autobiography         57.0
29            Classics         55.0
30   Christian Fiction         55.0
31          Psychology         52.0
32           New Adult         49.0
33              Health         49.0
34            Politics         45.0
35           Biography         43.0
36           Christian         37.0
37        Contemporary         33.0
38          Historical         20.0
39             Erotica         15.0
40            Cultural         15.0
41               Crime         15.0
42    Sports and Games         10.0
43              Novels          9.0
44            Suspense          8.0
45       Short Stories          8.0
46            Academic          5.0
47           Parenting          3.0
48       Adult Fiction          3.0
49          Paranormal          1.0

In [119]:
# Top 10 books with the highest stock quantity
query = """
SELECT
    title,
    category,
    stock_quantity
FROM books
WHERE category IS NOT NULL
AND category <> ''
ORDER BY stock_quantity DESC
LIMIT 10
"""

pd.read_sql_query(query,conn)

,title,category,stock_quantity
0,A Light in the Attic,Poetry,22.0
1,Tipping the Velvet,Historical Fiction,20.0
2,Soumission,Fiction,20.0
3,Sharp Objects,Mystery,20.0
4,Sapiens: A Brief History of Humankind,History,20.0
5,The Requiem Red,Young Adult,19.0
6,The Dirty Little Secrets of Getting Your Dream...,Business,19.0
7,The Coming Woman: A Novel Based on the Life of...,Default,19.0
8,The Boys in the Boat: Nine Americans and Their...,Default,19.0
9,The Black Maria,Poetry,19.0

In [120]:
# Total inventory value by category
query = """
SELECT
    category,
    ROUND(
        SUM(price * stock_quantity),
        2
    ) AS inventory_value
FROM books
WHERE category IS NOT NULL
AND category <> ''
GROUP BY category
ORDER BY inventory_value DESC
"""

pd.read_sql_query(query,conn)

              category  inventory_value
0              Default         46569.15
1           Nonfiction         32123.26
2       Sequential Art         23174.50
3              Fiction         21445.99
4        Add a comment         18315.24
5          Young Adult         16714.84
6              Fantasy         14199.01
7       Food and Drink         10347.51
8              Mystery          9496.48
9               Poetry          8601.81
10             Romance          8472.73
11           Childrens          7957.43
12  Historical Fiction          6946.26
13             History          6467.28
14              Horror          4472.98
15               Music          4161.89
16     Science Fiction          4043.35
17             Science          4042.70
18            Business          4019.64
19              Travel          3888.15
20            Thriller          3659.30
21      Womens Fiction          3207.83
22          Philosophy          2747.91
23                 Art          2673.58
24           Self Help          2571.68
25              Health          2515.70
26               Humor          2432.24
27            Politics          2394.69
28           New Adult          2342.31
29        Spirituality          2135.82
30            Classics          1888.61
31   Christian Fiction          1843.40
32       Autobiography          1793.46
33            Religion          1773.51
34           Christian          1712.47
35          Psychology          1701.92
36        Contemporary          1319.50
37           Biography          1227.29
38            Cultural           548.70
39          Historical           512.92
40              Novels           493.29
41            Suspense           466.64
42    Sports and Games           422.37
43             Erotica           287.85
44       Short Stories           287.04
45               Crime           164.55
46           Parenting           112.05
47            Academic            65.60
48       Adult Fiction            46.08
49          Paranormal            15.40

In [121]:
# Average price of books by rating
query = """
SELECT
    rating,
    ROUND(
        AVG(price),
        2
    ) AS average_price
FROM books
GROUP BY rating
ORDER BY rating
"""

pd.read_sql_query(query,conn)

   rating  average_price
0       1          34.56
1       2          34.81
2       3          34.69
3       4          36.09
4       5          35.37

In [122]:
# Minimum and maximum price of books by category
query = """
SELECT
    category,
    MIN(price) AS min_price,
    MAX(price) AS max_price
FROM books
WHERE category IS NOT NULL
AND category <> ''
GROUP BY category
ORDER BY max_price DESC
"""

pd.read_sql_query(query,conn)

              category  min_price  max_price
0              Romance      11.10      59.99
1              Fiction      10.60      59.98
2           Psychology      10.40      59.95
3       Food and Drink      11.05      59.92
4           Nonfiction      11.68      59.90
5             Thriller      12.84      59.71
6              History      11.45      59.64
7              Mystery      10.69      59.48
8        Add a comment      10.02      59.15
9        Autobiography      10.93      59.04
10             Default      10.23      58.87
11             Fantasy      12.16      58.75
12            Classics      14.82      58.63
13           New Adult      36.29      58.35
14            Suspense      58.33      58.33
15         Young Adult      10.00      58.14
16          Philosophy      15.94      58.11
17           Childrens      10.62      58.08
18              Horror      10.56      57.86
19      Sequential Art      10.16      57.62
20            Religion      21.87      57.49
21      Womens Fiction      13.73      57.36
22             Science      10.01      57.36
23              Poetry      14.19      57.31
24               Music      12.36      57.25
25              Travel      23.21      56.88
26            Politics      51.33      56.86
27        Spirituality      17.66      55.65
28  Historical Fiction      16.62      55.55
29               Humor      11.83      55.50
30     Science Fiction      10.65      54.86
31              Novels      54.81      54.81
32              Health      49.05      54.07
33           Christian      25.77      54.00
34        Contemporary      24.04      52.79
35           Self Help      12.08      52.15
36            Business      12.61      51.74
37    Sports and Games      24.42      51.22
38   Christian Fiction      17.97      49.97
39                 Art      10.29      49.05
40           Biography      16.85      48.19
41           Parenting      37.35      37.35
42            Cultural      36.58      36.58
43       Short Stories      35.88      35.88
44          Historical      15.79      29.87
45             Erotica      19.19      19.19
46          Paranormal      15.40      15.40
47       Adult Fiction      15.36      15.36
48            Academic      13.12      13.12
49               Crime      10.97      10.97

In [123]:
# Average stock quantity of books by category
query = """
SELECT
    category,
    ROUND(
        AVG(stock_quantity),
        1
    ) AS average_stock
FROM books
WHERE category IS NOT NULL
AND category <> ''
GROUP BY category
ORDER BY average_stock DESC
"""

pd.read_sql_query(query,conn)

              category  average_stock
0             Politics           15.0
1              Erotica           15.0
2             Cultural           15.0
3                Crime           15.0
4               Poetry           12.7
5               Health           12.3
6            Christian           12.3
7            Self Help           11.8
8         Spirituality           11.5
9             Business           11.1
10        Contemporary           11.0
11            Thriller           10.8
12      Food and Drink           10.6
13             History           10.1
14          Historical           10.0
15                 Art            9.3
16      Sequential Art            9.2
17   Christian Fiction            9.2
18             Mystery            9.1
19              Novels            9.0
20             Fiction            9.0
21          Nonfiction            8.9
22             Default            8.9
23         Young Adult            8.6
24            Religion            8.6
25           Biography            8.6
26               Music            8.5
27               Humor            8.4
28           New Adult            8.2
29              Travel            8.1
30            Suspense            8.0
31       Short Stories            8.0
32              Horror            8.0
33             Fantasy            7.9
34           Childrens            7.9
35     Science Fiction            7.8
36             Romance            7.7
37       Add a comment            7.7
38             Science            7.5
39          Philosophy            7.5
40  Historical Fiction            7.5
41          Psychology            7.4
42       Autobiography            6.3
43      Womens Fiction            5.4
44            Academic            5.0
45           Parenting            3.0
46       Adult Fiction            3.0
47            Classics            2.9
48    Sports and Games            2.0
49          Paranormal            1.0

In [ ]:
# Summary statistics of the books dataset
query = """
SELECT
    COUNT(*) AS total_books,
    COUNT(DISTINCT category) AS total_categories,
    ROUND(AVG(price),2) AS average_price,
    ROUND(AVG(rating),2) AS average_rating
FROM books
WHERE category IS NOT NULL
AND category <> ''
"""

pd.read_sql_query(query,conn)

   total_books  total_categories  average_price  average_rating
0          992                50          35.05            2.92

In [125]:
# Average price and rating of books by category (only categories with at least 10 books)
query = """
SELECT
    category,
    COUNT(*) AS books,
    ROUND(AVG(price),2) AS avg_price,
    ROUND(AVG(rating),2) AS avg_rating
FROM books
WHERE category IS NOT NULL
GROUP BY category
HAVING COUNT(*) >= 10
ORDER BY avg_rating DESC;
"""
pd.read_sql_query(query,conn)

              category  books  avg_price  avg_rating
0               Poetry     18      37.12        3.44
1                Humor     10      33.50        3.40
2          Young Adult     54      35.45        3.30
3   Historical Fiction     26      33.64        3.23
4              Fiction     65      36.07        3.18
5                Music     13      35.64        3.15
6              Fantasy     46      39.18        3.07
7       Womens Fiction     16      36.07        3.00
8       Sequential Art     74      34.66        2.99
9              Mystery     32      31.72        2.94
10             History     18      37.30        2.94
11             Science     14      33.09        2.93
12            Business     12      32.46        2.92
13      Food and Drink     30      31.41        2.90
14          Nonfiction    110      34.26        2.88
15             Default    150      34.35        2.85
16       Add a comment     67      35.80        2.76
17              Travel     11      39.79        2.73
18            Thriller     11      31.43        2.73
19              Horror     17      35.95        2.71
20             Romance     35      33.93        2.63
21           Childrens     29      32.64        2.62
22            Classics     19      36.55        2.47
23          Philosophy     11      33.56        2.36
24     Science Fiction     16      33.80        2.25

## Key Findings

- The dataset contains 1,000 books across multiple categories.
- Default, Nonfiction, and Sequential Art are among the largest categories.
- Several categories exhibit high average ratings, indicating strong reader satisfaction.
- Inventory value varies considerably across categories, highlighting differences in pricing and stock levels.
- Data quality assessment identified 8 records with missing enrichment information, resulting in a 99.2% enrichment success rate.

In [126]:
# Close connection
conn.close()